"""
Django settings for tcu_django project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os

# ------------------------------
# BASE_DIR
# ------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------
# Seguridad
# ------------------------------
SECRET_KEY = 'django-insecure-iy40(4qp$(5&r=y5((*o&f5imy2=3d#^$n3$#@$q7^!_#q_aig'
DEBUG = True
ALLOWED_HOSTS = []

# ------------------------------
# Aplicaciones instaladas
# ------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'solicitudes',
]

# ------------------------------
# Middleware
# ------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ------------------------------
# URL y WSGI
# ------------------------------
ROOT_URLCONF = 'tcu_django.urls'

WSGI_APPLICATION = 'tcu_django.wsgi.application'

# ------------------------------
# Templates
# ------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # puedes agregar rutas de templates adicionales aquí
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',  # necesario para {% static %}
            ],
        },
    },
]

# ------------------------------
# Base de datos
# ------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ------------------------------
# Validación de contraseñas
# ------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ------------------------------
# Internacionalización
# ------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ------------------------------
# Archivos estáticos
# ------------------------------
STATIC_URL = 'static/'

# Directorios adicionales donde Django buscará archivos estáticos esto es para que reconozca la carpeta static dentro de la app solicitudes
STATICFILES_DIRS = [
    BASE_DIR / 'solicitudes' / 'static',
]

# ------------------------------
# Default primary key field type
# ------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------------
# Configuración de Odoo
# ------------------------------
ODOO_URL = "http://localhost:8069"
ODOO_DB = "odooUIA"
ODOO_USER = "usuario_api"
ODOO_PASSWORD = "api1234"
